---
title: R for Data Analysis in Ecology
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
link-citations: yes
github-repo: datacarpentry/R-ecology-lesson
description: "This is an introduction to R designed for participants with no programming
experience. These lessons can be taught in 3/4 of a day. They start with some
basic information about R syntax, the RStudio interface, and move through how to
import CSV files, the structure of data.frame, how to deal with factors, how to
add/remove rows and columns, and finish with how to calculate summary statistics
for each level and a very brief introduction to plotting."
layout: lesson
root: .
lastupdated: March 21, 2016
documentclass: book
params:
  contributors: ["Sarah Supp", "John Blischak","Gavin Simpson","Tracy Teal","Greg Wilson","Diego Barneche"," Stephen Turner","Francois Michonneau"]
  maintainers: ["Francois Michonneau", "Auriel Fournier"]
  domain: Ecology
  topic: R for data analysis
  software: R
  dataurl: http://dx.doi.org/10.6084/m9.figshare.1314459
  status: Teaching
--- 

# Overview

**Content Contributors: `r paste(params$contributors, collapse=', ')`**


**Lesson Maintainers: `r paste(params$maintainers, collapse=', ')`**


**Lesson status: `r params$status`**

<!--
  [Information on Lesson Status Categories]()
-->

<!-- ###### INDEX OF LESSONS ON THIS TOPIC ###### -->

## Lessons

1. [Lesson 00 Before we start](before-we-start.html)
2. [Lesson 01 Introduction to R](intro-to-r.html)
3. [Lesson 02 Starting with data](starting-with-data.html)
4. [Lesson 03 Introducing `data.frame`](data-frames.html)
5. [Lesson 04 Aggregating and analyzing data with dplyr](data-manip-dplyr.html)
6. [Lesson 05 Data visualization with ggplot2](vis-ggplot2.html)
7. [Lesson 06 R and SQL](r-and-sql.html)


## Data

Data files for the lesson are available here: <`r params$dataurl`>

Please download the *\*.csv* (Comma Separated Value) files: *species.csv*, *plots.csv*, *surveys.csv*, and *combined.csv*.

### Requirements

Data Carpentry's teaching is hands-on, so participants are encouraged to use
their own computers to insure the proper setup of tools for an efficient workflow.
*These lessons assume no prior knowledge of the skills or tools*, but working
through this lesson requires working copies of the software described below.
To most effectively use these materials, please make sure to install everything
*before* working through this lesson.

```{r, child="_r-setup.Rmd"}
```

## Other resources

* [Why use R?](other/r-motivation.html)

<p><strong>Twitter</strong>: @datacarpentry</p>
